### ISSUE TITLE
Security errors

### ISSUE THREAD

**Issue by blahbloo** [prairiesnpr/hass-tdameritrade#12]
Went thru and created a TDA developer account, got the Consumer Key, added the callback url as described, but upon installing the HA integration I get forwarded to TDA page preventing further access and saying it could be due to a technical error or "the client application may be an attempt to fraudulently access your account".

Tips on this one?

**Comment by timelf123** [comment]
![image](https://user-images.githubusercontent.com/2816999/134754333-a9c60428-42d9-4d0d-bad1-d226486e4443.png)
`https://auth.tdameritrade.com/auth?response_type=code&client_id=FOO&redirect_uri=https://BAR.duckdns.org/auth/external/callback&state=FOOBAR`

**Comment by prairiesnpr** [comment]
I had to append @AMER.OAUTHAP to my consumer key value. It looks like this is required now.

You may still have issues though, after the last home assistant upgrade, the integration isn't completing the setup steps and fails to create the account sensors.  I'm still digging into the cause.

**Comment by blahbloo** [comment]
> I had to append @AMER.OAUTHAP to my consumer key value. It looks like this is required now.
> 
> You may still have issues though, after the last home assistant upgrade, the integration isn't completing the setup steps and fails to create the account sensors. I'm still digging into the cause.

Thanks for the response. I did eventually figure the @AMER.OATHAP requirement and managed to get that part working. But as you also mentioned, I'm unable to create account sensors. The get_quote and place_order services appear to have been generated (though, I have not tested them), but I don't see any sensors to just get my account info as of yet.

**Comment by prairiesnpr** [comment]
@blahbloo  I just pushed a release that fixes the account sensor creation issue.  Please let me know if that fixes the issue for you.

**Comment by blahbloo** [comment]
> @blahbloo I just pushed a release that fixes the account sensor creation issue. Please let me know if that fixes the issue for you.

It does fix the sensor creation issue, thanks. How often should I expect the sensor to poll for up-to-date data? I've had the sensor installed for about 24hr, but there's been no updates to the account value.

**Comment by prairiesnpr** [comment]
> It does fix the sensor creation issue, thanks. How often should I expect the sensor to poll for up-to-date data? I've had the sensor installed for about 24hr, but there's been no updates to the account value.

The scan interval changes based on if the market is open or not.  It updates every 10 seconds for an open market and every 5 min for a closed market. 

The sensor value is either cash available for tradeing or available funds, depending on if you have a cash account or margin account, so that probably hasn't changed.  If you are looking for the current account value, look at either liquidation value or long stock value in the sensor attributes.
